//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.Person.Registratio.CrossCuting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SL.Person.Registratio.CrossCuting.Resources.ResourceMessagesValidation", typeof(ResourceMessagesValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados do endereço..
        /// </summary>
        public static string AddressCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("AddressCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento da pessoa que deseja adicionar o endereço..
        /// </summary>
        public static string AddressCommandValidation_RequestInvalid_Document {
            get {
                return ResourceManager.GetString("AddressCommandValidation_RequestInvalid_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatória..
        /// </summary>
        public static string AddressValidation_City {
            get {
                return ResourceManager.GetString("AddressValidation_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro é obrigatório..
        /// </summary>
        public static string AddressValidation_Neighborhood {
            get {
                return ResourceManager.GetString("AddressValidation_Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório..
        /// </summary>
        public static string AddressValidation_Number {
            get {
                return ResourceManager.GetString("AddressValidation_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório..
        /// </summary>
        public static string AddressValidation_State {
            get {
                return ResourceManager.GetString("AddressValidation_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro é obrigatório..
        /// </summary>
        public static string AddressValidation_Street {
            get {
                return ResourceManager.GetString("AddressValidation_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é obrigatório..
        /// </summary>
        public static string AddressValidation_ZipCode {
            get {
                return ResourceManager.GetString("AddressValidation_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados do contato.
        /// </summary>
        public static string ContactCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("ContactCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento da pessoa que deseja adicionar o contato..
        /// </summary>
        public static string ContactCommandValidation_RequestInvalid_Document {
            get {
                return ResourceManager.GetString("ContactCommandValidation_RequestInvalid_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD é obrigatório..
        /// </summary>
        public static string ContactValidation_DDD {
            get {
                return ResourceManager.GetString("ContactValidation_DDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone é obrigatório..
        /// </summary>
        public static string ContactValidation_PhoneNumber {
            get {
                return ResourceManager.GetString("ContactValidation_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço não encontrado..
        /// </summary>
        public static string FindAddressByZipCodeValidation_NotFound {
            get {
                return ResourceManager.GetString("FindAddressByZipCodeValidation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CEP do endereço..
        /// </summary>
        public static string FindAddressByZipCodeValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindAddressByZipCodeValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número do DDD e Celular..
        /// </summary>
        public static string FindPersonByContactNumberQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPersonByContactNumberQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número do Documento..
        /// </summary>
        public static string FindPersonByDocumentQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPersonByDocumentQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome da pessoa que deseja pesquisar..
        /// </summary>
        public static string FindPersonByNameQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPersonByNameQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento do paciente ou o documento do entrevistador..
        /// </summary>
        public static string InsertInterviewCommandValidation_DataRequestInvalid {
            get {
                return ResourceManager.GetString("InsertInterviewCommandValidation_DataRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da entrevista..
        /// </summary>
        public static string InsertInterviewCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("InsertInterviewCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da pessoa..
        /// </summary>
        public static string InsertPersonCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("InsertPersonCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada..
        /// </summary>
        public static string PersonRegistration_InstanceInvalid {
            get {
                return ResourceManager.GetString("PersonRegistration_InstanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrevistador não encontrado..
        /// </summary>
        public static string PersonRegistrationInterviewer_InstanceInvalid {
            get {
                return ResourceManager.GetString("PersonRegistrationInterviewer_InstanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefeiro não encontrado..
        /// </summary>
        public static string PersonRegistrationLabore_InstanceInvalid {
            get {
                return ResourceManager.GetString("PersonRegistrationLabore_InstanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestranete não encontrado..
        /// </summary>
        public static string PersonRegistrationSpeaker_InstanceInvalid {
            get {
                return ResourceManager.GetString("PersonRegistrationSpeaker_InstanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do documento é obrigatório..
        /// </summary>
        public static string PersonRegistrationValidation_DocumentNumber {
            get {
                return ResourceManager.GetString("PersonRegistrationValidation_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório.
        /// </summary>
        public static string PersonRegistrationValidation_Name {
            get {
                return ResourceManager.GetString("PersonRegistrationValidation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistido não encontrado..
        /// </summary>
        public static string PersonRegistrationWatched_InstanceInvalid {
            get {
                return ResourceManager.GetString("PersonRegistrationWatched_InstanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento do paciente ou o documento do tarefeiro..
        /// </summary>
        public static string PrecenceCommandValidation_DataRequestInvalid {
            get {
                return ResourceManager.GetString("PrecenceCommandValidation_DataRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da pessoa..
        /// </summary>
        public static string UpdatePersonCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("UpdatePersonCommandValidation_RequestInvalid", resourceCulture);
            }
        }
    }
}
