//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.Person.Registration.CrossCuting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SL.Person.Registration.CrossCuting.Resources.ResourceMessagesValidation", typeof(ResourceMessagesValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados do endereço..
        /// </summary>
        public static string AddressCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("AddressCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento da pessoa que deseja adicionar o endereço..
        /// </summary>
        public static string AddressCommandValidation_RequestInvalid_Document {
            get {
                return ResourceManager.GetString("AddressCommandValidation_RequestInvalid_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados do contato.
        /// </summary>
        public static string ContactCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("ContactCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento da pessoa que deseja adicionar o contato..
        /// </summary>
        public static string ContactCommandValidation_RequestInvalid_Document {
            get {
                return ResourceManager.GetString("ContactCommandValidation_RequestInvalid_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o &apos;Id&apos; da pessoa..
        /// </summary>
        public static string DeletePersonCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("DeletePersonCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CEP do endereço..
        /// </summary>
        public static string FindAddressByZipCodeValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindAddressByZipCodeValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pesquisa não retornou nenhum resultado..
        /// </summary>
        public static string FindPeopleQueryValidation_NotFound {
            get {
                return ResourceManager.GetString("FindPeopleQueryValidation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome da pessoa que deseja pesquisar..
        /// </summary>
        public static string FindPeopleQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPeopleQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o tipo da pessoa..
        /// </summary>
        public static string FindPeopleTypeQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPeopleTypeQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número do DDD e Celular..
        /// </summary>
        public static string FindPersonByContactNumberQueryValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPersonByContactNumberQueryValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o &apos;Id&apos; da pessoa.
        /// </summary>
        public static string FindPersonByIdValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("FindPersonByIdValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o documento do paciente ou o documento do entrevistador..
        /// </summary>
        public static string InsertInterviewCommandValidation_DataRequestInvalid {
            get {
                return ResourceManager.GetString("InsertInterviewCommandValidation_DataRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da entrevista..
        /// </summary>
        public static string InsertInterviewCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("InsertInterviewCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa já está cadastrada..
        /// </summary>
        public static string InsertPersonCommandHandler_Found {
            get {
                return ResourceManager.GetString("InsertPersonCommandHandler_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da pessoa..
        /// </summary>
        public static string InsertPersonCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("InsertPersonCommandValidation_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o &apos;Id&apos; ou a lista de escala..
        /// </summary>
        public static string InsertWorkSchedulesCommand_RequestInvalid {
            get {
                return ResourceManager.GetString("InsertWorkSchedulesCommand_RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o &apos;Id&apos; do paciente..
        /// </summary>
        public static string PrecenceCommandValidation_DataRequestInvalid {
            get {
                return ResourceManager.GetString("PrecenceCommandValidation_DataRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o &apos;Id&apos; do tarefeiro..
        /// </summary>
        public static string PresenceAssignmentCommandValidation_RequestInvalid_Id {
            get {
                return ResourceManager.GetString("PresenceAssignmentCommandValidation_RequestInvalid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A presença para o tarefeiro já foi confirmada..
        /// </summary>
        public static string PresenceAssignmentCommandValidation_RequestInvalid_Presence {
            get {
                return ResourceManager.GetString("PresenceAssignmentCommandValidation_RequestInvalid_Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da pessoa..
        /// </summary>
        public static string UpdatePersonCommandValidation_RequestInvalid {
            get {
                return ResourceManager.GetString("UpdatePersonCommandValidation_RequestInvalid", resourceCulture);
            }
        }
    }
}
